$(document).ready(function(){
	$('#personal').load("personal.php");
	$('#newbook').load("newbook.php");
	$('#searchPage').load("search.php");
	$('#books').load("books.php");
	$('#deletePage').load("delete.php");
	$('#borrow').load("borrow.php");
	$('#listborrows').load("listBorrow.php");
	$('#return').load("return.php");
});
